### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xinJOBS** [Valdecy/pyMultiobjective#1]
from pyMultiobjective.algorithm import non_dominated_sorting_genetic_algorithm_III

# Import Test Functions. Available Test Functions: Dent, DTLZ1, DTLZ2, DTLZ3, DTLZ4, DTLZ5, DTLZ6, DTLZ7, Fonseca-Fleming, Kursawe, Poloni, Schaffer1, Schaffer2, ZDT1, ZDT2, ZDT3, ZDT4, ZDT6, Viennet1, Viennet2, Viennet3 
from pyMultiobjective.test_functions import dent_f1, dent_f2

# OR Define your Own Custom Function. The function input should be a list of values, 
# each value represents a dimenstion (x1, x2, ...xn) of the problem.

# Run NSGA III
parameters = {
	'references': 5,
	'min_values': (-5, -5),
	'max_values': (5, 5),
	'mutation_rate': 0.1,
	'generations': 1500,
	'mu': 1,
	'eta': 1,
	'k': 2, 
	'verbose': True
}
sol = non_dominated_sorting_genetic_algorithm_III(list_of_functions = [dent_f1, dent_f2], **parameters)
Thank you very much for sharing, this code is very good, can I ask you a question? What do the mu and eat parameters in the code mean? What is the impact of the different values on the optimization algorithm? What is the impact on the results? I'm looking forward to your reply.

**Comment by Valdecy** [comment]
Hello there! mu is the mutation operator constant, and eta is the crossover operator constant. You should test the impacts by changing their values for different problems - in other words - performing a sensibility analysis and seeing what you got.
